import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import ts from "typescript";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const sourcePath = path.join(root, "lib/data/places.ts");
const generatedModulePath = path.join(root, "work/generated-places.mjs");
const seedPath = path.join(root, "supabase/seed.sql");

function sqlString(value) {
  if (value === null || value === undefined) {
    return "null";
  }

  return `'${String(value).replaceAll("'", "''")}'`;
}

function sqlNumber(value) {
  return value === null || value === undefined ? "null" : String(value);
}

function sqlBoolean(value) {
  return value ? "true" : "false";
}

function sqlTextArray(values) {
  if (!values.length) {
    return "array[]::text[]";
  }

  return `array[${values.map(sqlString).join(", ")}]::text[]`;
}

async function loadPlaces() {
  const source = await fs.readFile(sourcePath, "utf8");
  const transpiled = ts.transpileModule(source, {
    compilerOptions: {
      module: ts.ModuleKind.ES2022,
      target: ts.ScriptTarget.ES2022,
      verbatimModuleSyntax: false,
    },
  });

  await fs.mkdir(path.dirname(generatedModulePath), { recursive: true });
  await fs.writeFile(generatedModulePath, transpiled.outputText);

  const generated = await import(`${pathToFileURL(generatedModulePath).href}?v=${Date.now()}`);
  return generated.samplePlaces;
}

const places = await loadPlaces();

const columns = [
  "id",
  "name",
  "slug",
  "category",
  "description",
  "short_description",
  "address",
  "city",
  "country",
  "latitude",
  "longitude",
  "website_url",
  "phone",
  "email",
  "image_url",
  "source",
  "source_id",
  "tags",
  "is_sponsored",
  "sponsored_priority",
  "is_active",
  "rating",
  "opening_hours",
  "created_at",
  "updated_at",
];

const rows = places.map((place) => [
  sqlString(place.id),
  sqlString(place.name),
  sqlString(place.slug),
  sqlString(place.category),
  sqlString(place.description),
  sqlString(place.shortDescription),
  sqlString(place.address),
  sqlString(place.city),
  sqlString(place.country),
  sqlNumber(place.latitude),
  sqlNumber(place.longitude),
  sqlString(place.websiteUrl),
  sqlString(place.phone),
  sqlString(place.email),
  sqlString(place.imageUrl),
  sqlString(place.source),
  sqlString(place.sourceId),
  sqlTextArray(place.tags),
  sqlBoolean(place.isSponsored),
  sqlNumber(place.sponsoredPriority),
  sqlBoolean(place.isActive),
  sqlNumber(place.rating),
  sqlString(place.openingHours),
  sqlString(place.createdAt),
  sqlString(place.updatedAt),
]);

const updates = columns
  .filter((column) => column !== "id")
  .map((column) => `${column} = excluded.${column}`)
  .join(",\n  ");

const sql = `-- Generated by npm run seed:places.\n-- Run supabase/schema.sql first, then run this file in Supabase SQL Editor.\n\ninsert into public.places (${columns.join(", ")})\nvalues\n${rows
  .map((row) => `  (${row.join(", ")})`)
  .join(",\n")}\non conflict (id) do update set\n  ${updates};\n`;

await fs.writeFile(seedPath, sql);
console.log(`Wrote ${places.length} places to ${path.relative(root, seedPath)}.`);
